# Generated by Django 4.2 on 2023-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post.img', upload_to='img/', verbose_name='Изображение'),
        ),
    ]
